### ISSUE TITLE
If table type name is passed to to structure data ignore property is broken

### ISSUE THREAD

**Issue by BrandonJJohnson** [davidwest/FluidDbClient#8]
Example: 

var PrinterList = printerList.ToStructuredData("HKEPrinter")

By specify the table type name StructuredDataBuilder(string tableTypeName, params SqlMetaData[] preOrderedMetaData) gets called which does not correctly handle the ignore property.

**Comment by davidwest** [comment]
Eesh, looks like we have an ambiguous specification problem (CLR type vs. table type name).
Let me figure out mapping collision rules, and get back to the drawing board on that one.

**Comment by BrandonJJohnson** [comment]
There may also be issues with stored procedures and ignore.  The example in Sandbox works but I have not been able to get a table type specified through structure data to work which has a TVP specified with a different column count than the mapping.

**Comment by davidwest** [comment]
Fixed in 1.1.3
