### ISSUE TITLE
Consider rewriting core of application to make use of Datasets / DataTables

### ISSUE THREAD

**Issue by BrandonJJohnson** [davidwest/FluidDbClient#9]
Might be worth looking into dropping support of .Net frameworks prior to .Net Core 2.0 and rewriting the core of the application to use datasets / datatables which in the process would amount of code and also make it easier to work with table types in SQL.

**Comment by davidwest** [comment]
I'd be on board with that.  We could then target the following:

DataTable ManagedDbQuery.GetDataTable(...);
DataSet ManagedDbQuery.GetDataSet(...);

var dt = Db.GetDataTable(...);
var dt = DbProc.GetDataTable(...);
var ds = Db.GetDataSet(...);
var ds = DbProc.GetDataSet(...);

Correct me if I'm wrong, but I think the only other code change required to make the jump to >= .NET Standard 2.0 would be reflection used in mapping.

**Comment by davidwest** [comment]
Added this in 1.1.4
